# Config file for automatic testing at travis-ci.org
language: python

python:
  - "3.5"
  - "2.7"

before_install:
  - pip install codecov

install: pip install -r requirements_test.txt

services:
  - postgresql

script: python runtests.py

after_success:
  - codecov
